name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Compile
        run: npm run compile

      - name: Run unit tests
        run: npm test